broadinstitute/leonardo-cron-jobs

- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala
forgot to run sql unit tests...
Impact is we would update `Deleted` disks/clusters to `Deleted` with a more recent `destroyedDate`
> Fix sql bug

- project/Dependencies.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- resource-validator/src/test/resources/reference.conf
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderSpec.scala
https://broadworkbench.atlassian.net/browse/IA-2183
In previous PR, I added `id` field to `Disk`, since we didn't have unit test, this was overlooked...I added a unit test, which people can run locally..altho running unit tests for db is not set up in CI yet
Running unit test without the fix will result in
```
Query0[Disk] defined at DbReader.scala:24
select pd1.googleProject, pd1.name from PERSISTENT_DISK as pd1 where
pd1.status="Deleted" and
NOT EXISTS
(
SELECT *
FROM PERSISTENT_DISK pd2
WHERE pd1.googleProject = pd2.googleProject and pd1.name = pd2.name
and pd2.status != "Deleted"
)
✓ SQL Compiles and TypeChecks
✕ C01 googleProject VARCHAR (VARCHAR) NOT NULL  →  Long
VARCHAR (VARCHAR) is ostensibly coercible to Long according to the
JDBC specification but is not a recommended target …
```
> IA-2183 fix a bug

- core/src/main/scala/com/broadinstitute/dsp/CheckRunner.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/BucketRemover.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedDiskChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/KubernetesClusterRemover.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/package.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedDiskChecker.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedKubernetesClusterChecker.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/package.scala
previously we weren't very consistent in terms of where reports will be sent to. This PR makes it more consistent.
All reports generated from resource-validator will be under
`leonardo-resource-validator-report-{env}/resource-validator/${check-type}/???`
All reports generated from zombie-monitor will be under
`leonardo-resource-validator-report-{env}/zombie-monitor/${check-type}/???`
We should probably rename the bucket name itself as well since we split things into multiple cron jobs..But that refactoring will require more changes, we can do it another time
> [no ticket] make bucket path more consistent

- .github/workflows/createPullRequest.yml
awesome-global-contributions/action-yq@v0.1.2 requires a `file` parameter, which will require us to add a script in terra-helm.
Chelsea suggested using in house action instead, which was added in https://github.com/DataBiosphere/github-actions/pull/11
> use inhouse yq action

- resource-validator/src/main/resources/reference.conf
- resource-validator/src/test/resources/reference.conf
`runtime-checker-config` is needed, but I accidentally added to the `reference.conf` in test, hence unit test is working fine, but it's actually missing for resource-validator
> [no ticket] fix bug

- resource-validator/src/main/resources/reference.conf
- zombie-monitor/src/main/resources/reference.conf
Since `report-destination-bucket` is referenced by another config in reference.conf, it needs to be present in reference.conf. Its actual value will be replaced by config file passed by `-D`..I think leonardo uses the same pattern as well
Tested in my own namespace
> fix config bug

- README.md
- core/src/main/scala/com/broadinstitute/dsp/models.scala
- core/src/test/scala/com/broadinstitute/dsp/DBTestHelper.scala
- core/src/test/scala/com/broadinstitute/dsp/Generators.scala
- project/Dependencies.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredKubernetesClusterChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/Main.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbQueryBuilderSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetDeletedAndErroredKubernetesClustersSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetDeletedOrErroredNodepoolsSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetKubernetesClustersToDeleteSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredKubernetesClusterCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitDependenciesHelper.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/mocks.scala
Tested using unit tests and also running the two new checkers (for KubernetesClusters and Nodepools) locally and seeing that nodepool anomalies were detected in google project `broad-dsde-dev` and verified that these anomalies were indeed marked as `ERROR` in the leo db but still existed in google
> [IA-2270] Delete deleted and errored k8s clusters and nodepools in Google

- core/src/main/scala/com/broadinstitute/dsp/CheckRunner.scala
- core/src/test/scala/com/broadinstitute/dsp/CronJobsTestSuite.scala
- project/Dependencies.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/BucketRemover.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedDiskChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredKubernetesClusterChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/InitBucketChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/KubernetesClusterRemover.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedDiskCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredKubernetesClusterCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/KubernetesClusterRemoverSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/mocks.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedDiskChecker.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedKubernetesClusterChecker.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredNodepoolChecker.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredRuntimeChecker.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ZombieMonitor.scala
- zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredNodepoolCheckerSpec.scala
- zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredRuntimeCheckerSpec.scala
- Uses new version of cats.mtl which change `ApplicativeAsk` -> `Ask` 
- Uses new wb-libs function publishOne instead of the former streaming approach
- Refactors a mock and decoder to wb-libs
> [IA-2305] Refactor some code to wb-libs

- core/src/main/scala/com/broadinstitute/dsp/checkerDeps.scala
- core/src/main/scala/com/broadinstitute/dsp/models.scala
- core/src/test/scala/com/broadinstitute/dsp/Generators.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/KubernetesClusterRemover.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitDependenciesHelper.scala
Tested against my fiab 
message successfully published:
{"@timestamp":"2020-11-20T15:19:19.725Z","@version":"1","message":"{\"response\":\"()\",\"result\":\"Succeeded\",\"traceId\":\"50c24029-23d3-4bd3-b68e-2e87e3063f41\",\"googleCall\":\"com.google.cloud.pubsub.v1.Publisher.publish(<ByteString@5a56c8b7 size=138 contents=\\\"{\\\\\\\"messageType\\\\\\\":\\\\\\\"deleteNodepool\\\\\\\",\\\\\\\"nodepoolId\\\\\\\":22...\\\">)\",\"duration\":\"448 milliseconds\"}","logger_name":"com.broadinstitute.dsp.resourceValidator.ResourceValidator","thread_name":"Gax-11","severity":"INFO","level_value":20000,"traceId":"50c24029-23d3-4bd3-b68e-2e87e3063f41","googleCall":"com.google.cloud.pubsub.v1.Publisher.publish(<ByteString@5a56c8b7 size=138 contents=\"{\\\"messageType\\\":\\\"deleteNodepool\\\",\\\"nod …
> [IA-2347] ResourceValidator publishes DeleteNodepoolMessage

- core/src/main/scala/com/broadinstitute/dsp/checkerDeps.scala
- project/Dependencies.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeChecker.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/Main.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeCheckerSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeCheckerSpec.scala
In non-dry runs, the deleted and errored runtime checkers first check if billing is enabled before attempted to delete the runtime. 
This relies on the merged wb-libs PR is here: https://github.com/broadinstitute/workbench-libs/pull/474/files
> [IA-2352] add check if billing is enabled to checkers

- project/Dependencies.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
https://broadworkbench.atlassian.net/browse/IA-2415
only scan runtimes, disks that are deleted in the last 90 days. Assuming that runtimes/disks deleted earlier then 90 days have already been checked many times
> IA-2415 update query to only care about recently deleted runtimes

- project/Dependencies.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ZombieMonitor.scala
https://broadworkbench.atlassian.net/browse/IA-2490
```
Exception in thread "main" java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
```
This error seems to happen more frequently recently in resource-validator. I asked in doobie gitter channel, the suggestion is read all records into memory instead because `.stream.transact(xa)` only closes connection once the `Stream` terminates.
I'm thinking we can reduce the number of records even further by reducing number of days we look back. Since resource-validator runs every day, so technically, this should totally be fine. …
> [no ticket] Attempt to make db connection error less often

- README.md
- core/src/main/scala/com/broadinstitute/dsp/models.scala
- core/src/test/scala/com/broadinstitute/dsp/Generators.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedDiskChecker.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala
Update ResourceValidator to delete metadata disks from Google if cleaning up the corresponding data disk. Relies on this PR for Leo (https://github.com/DataBiosphere/leonardo/pull/2069) to update the naming convention for Galaxy metadata disks to be discoverable using the PERSISTENT_DISK table in the Leo DB.
Tested successfully on dev
Made a Galaxy app then detached the disks in Google and set them to "deleted" status in the DB. Ran the cronjob and both disks were deleted from Google
Before:
After:
> Update Resource Validator to handle the 2nd Galaxy disk (IA-2741)

- janitor/src/main/scala/com/broadinstitute/dsp/janitor/DbReader.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala
https://broadworkbench.atlassian.net/browse/IA-2977
Part of the refactoring to support Azure, `clusterRuntime` is renamed to `runtimeName`, `googleProject` is renamed to `cloudContext` for CLUSTER, and PD tables
> IA-2977 fix bugs from DB refactoring

- .github/workflows/createPullRequest.yml
Hello, we [recently migrated all Terra Helm charts out of terra-helm and into terra-helmfile](https://github.com/broadinstitute/terra-helmfile/pull/2107), as part of our plan to merge the two repositories.
This PR updates the leonardo-cron-jobs to point at terra-helmfile.
> DDO-1818 Configure leonardo-cronjobs workflow to point at terra-helmfile

- janitor/src/main/scala/com/broadinstitute/dsp/janitor/Main.scala
- nuker/src/main/scala/com/broadinstitute/dsp/nuker/Main.scala
- project/Dependencies.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/Main.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/Main.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ZombieMonitor.scala
https://broadworkbench.atlassian.net/browse/IA-3005
In current code, because `goog-compute-???` threads aren't daemon threads, they'll prevent JVM from shutting down properly. It shutsdown just fine via `sbt` for some reason, but issue is exposed when deployed running in a container.
See error
```
Non-daemon threads currently preventing JVM termination: - 299: Thread[DestroyJavaVM,5,main]
```
Depends on https://github.com/broadinstitute/workbench-libs/pull/864
> IA-3005 fix shutdown issue

- project/Dependencies.scala
Similar to https://github.com/broadinstitute/leonardo-cron-jobs/pull/174.
Relevant wb-libs PR https://github.com/broadinstitute/workbench-libs/pull/872
The previous PR fixed zombie monitor. But the resourceValidator and janitor uses pubsub, which also uses non daemon threads.
> IA-3005 bump wb-libs

- core/src/main/scala/com/broadinstitute/dsp/CheckRunner.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/Janitor.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/KubernetesClusterRemover.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/KubernetesClusterRemoverSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/NodepoolRemoverSpec.scala
In Dev, we keep getting messages about delete kubernetes clusters. Those clusters live in billing projects that are already disabled, so when leo tries to disable, things will error out. Next time cron job runs, these clusters will get picked up again, and leo will fail to delete again.
This changes the cron job to ignore clusters if its project doesn't have billing enabled
> [no ticket] not try to delete kubernetes cluster if billing is disabled

- core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala
Dev Cron job is still erroring. This is because of existing Azure entries in the DB. The Cron job will try to check these entries which correctly threw the NotImplementedError. We removed the error throwing in this case. I added a TODO to correctly implement this once we do support Azure
> [IA-3281] dealing with existing azure entries in dev

- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbQueryBuilderSpec.scala
https://broadworkbench.atlassian.net/browse/IA-3480
Disks that're in "Deleting" status means at some point there was user request to delete these disks, but somehow they're stuck in deleting. So we're discovering these disks and deleting them in GCP.
Once these disks are actually deleted in GCP, they'll be picked up by zombie monitor and leo DB will reflect the right status from then on.
> IA-3480 delete "Deleting" disk as well

- project/Dependencies.scala
- project/Merging.scala
https://broadworkbench.atlassian.net/browse/IA-3631
resource-validator on dev is failing with
```
stack_trace: "java.lang.NoClassDefFoundError: Could not initialize class com.azure.core.implementation.ReflectionUtilsApi
at com.azure.core.http.rest.ResponseExceptionConstructorCache.locateExceptionConstructor(ResponseExceptionConstructorCache.java:38)
at com.azure.core.http.rest.ResponseExceptionConstructorCache.lambda$get$0(ResponseExceptionConstructorCache.java:32)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
at com.azure.core.http.rest.ResponseExceptionConstructorCache.get(ResponseExceptionConstructorCache.java:32)
at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:395)
at …
```
> IA-3631 Attempt to fix lib version conflicts

- core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala
- project/Merging.scala
https://broadworkbench.atlassian.net/browse/IA-3631
Resource validator is currently broken becuz I think `sbt assembly` removed some of the classes.
> IA-3631 Fix assembly

- core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala
https://broadworkbench.atlassian.net/browse/IA-3858
For zombie monitor, update the DB reader to ignore Azure nodepool for now.
For resource-validator, update the SQL query to exclude Azure from the start.
> IA-3858 ignore Azure nodepool, cluster

- README.md
- core/src/main/scala/com/broadinstitute/dsp/models.scala
- core/src/test/scala/com/broadinstitute/dsp/DbTestHelper.scala
- core/src/test/scala/com/broadinstitute/dsp/Generators.scala
- janitor/src/main/resources/reference.conf
- janitor/src/main/resources/reference.conf.example
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/DbReader.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/Janitor.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/Main.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/StuckAppReporter.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbQueryBuilderSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbReaderGetAppStuckToReportSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbReaderGetKubernetesClustersToDeleteSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbReaderGetNodepoolsToDeleteSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/StuckAppReporterSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/mocks.scala
- resource-validator/src/main/resources/reference.conf.example
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbQueryBuilderSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetDeletedAndErroredKubernetesClustersSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetDeletedOrErroredNodepoolsSpec.scala
- zombie-monitor/src/main/resources/reference.conf.example
- zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DbReaderSpec.scala
https://broadworkbench.atlassian.net/browse/IA-3883
This PR does the following:
- Adds a query in the DbReader to query apps stuck in `creating` for more than 2 hours, or stuck in `deleting` for more than one hour (only one query for both cases for now)
- Reports  the result of that query in the google cloud logs
I was able to successfully run the query against my cloned instance of the leo DB, but would like some eyes on the logging front, happy to pair review!
Note that all unit tests, including the ones making use of the local leo DB are passing locally :)
> [IA-3883] Detect apps stuck in creating or deleting states

- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
Noticed errors in dev resource-validator: 
```
java.lang.NumberFormatException: For input string: "ke06fdd7-9d14-43a7-85d7-f7c48cf1de59"
```
https://ap-argocd.dsp-devops.broadinstitute.org/applications/leonardo-dev?resource=
In my [last PR](https://github.com/broadinstitute/leonardo-cron-jobs/pull/256/files#diff-8a5ea2275ca26bd7ff749af0903692597a4896d0857ebf98e4f66ba7fe553e2bR112) I added `id` to `KubernetesCluster` model but neglected to update all the queries.
I double-checked zombie/janitor and those seem correct -- just resource-validator was missed.
> [IA-3623 follow up] Fix SQL in resource-validator

- README.md
Based on our conversations @rtitle, I wanted to update the documentation for this repo on confluence (https://broadworkbench.atlassian.net/wiki/spaces/IA/pages/2699558951/Leonardo+Cron+Jobs), as well as the Readme.
Explaining what is feasible for Azure vs. Google is becoming more and more important.
> [IA-4022] update documentation and link new confluence page

- .github/workflows/createPullRequest.yml
Fixing some weirdness that happened when merging the previous PR: https://github.com/broadinstitute/terra-helmfile/pull/4515/files 
I think the Resource Validator cron job god renamed as part of the migration off fc-dev, and it's the first time we updated the cron job since then 😬
> [IA-4459] update the PR generating yml file

- README.md
- build.sbt
- core/src/test/scala/com/broadinstitute/dsp/DbTestHelper.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbQueryBuilderSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbReaderGetAppStuckToReportSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbReaderGetKubernetesClustersToDeleteSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/DbReaderGetNodepoolsToDeleteSpec.scala
- project/Dependencies.scala
- project/plugins.sbt
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbQueryBuilderSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetDeletedAndErroredKubernetesClustersSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetDeletedOrErroredNodepoolsSpec.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderGetDeletingRuntimesSpec.scala
- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala
- zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DbReaderSpec.scala
https://precisionmedicineinitiative.atlassian.net/browse/RW-10808
When GKE cluster or nodepool gets deleted, we should make sure APP_USAGE table is updated to record `stopTime` if there's a record for the apps on these deleted cluster or nodepool. This PR updates `stopTime` to app's `dateAccessed` time, which is the last time Leonardo knows that a user accessed the app.
I tested the query against dev DB, and I think unit test has pretty good coverage.
> RW-10808 update APP_USAGE table

- core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala
- core/src/main/scala/com/broadinstitute/dsp/models.scala
- core/src/test/scala/com/broadinstitute/dsp/Generators.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/DbReader.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/NodepoolRemover.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/NodepoolRemoverSpec.scala
- project/Dependencies.scala
https://precisionmedicineinitiative.atlassian.net/browse/RW-11733
Currently, the nodepool remover and kubernetes cluster remover run independently. This has an issue where if the nodepool candidate is on a kubernetes cluster candidate, then the kubernetes cluster deletion will fail with the following error from GCP.
```
com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Operation operation-1705676420312-89e6513c-2489-4804-b954-e8a633291ba4 is currently deleting a node pool for cluster k0a6c961-d599-4f5c-9dea-c01e15c9293a. Please wait and try again once it is done.
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:102)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.j …
```
> RW-11733 Fix a bug in janitor where in-progress nodepool is blocking kubernetes cluster deletion

- core/src/main/scala/com/broadinstitute/dsp/DbTransactor.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
We recently noticed that some PDs may have been marked as "Deleted" but without `destroyedDate` due to a bug. For these disks, cron job currently isn't validating whether they're indeed deleted in GCP, which can cause unexpected expense.
This PR adds these PDs to be scanned by the resource validator
> IA-4823  add destroyedDate condition

- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
Reverts broadinstitute/leonardo-cron-jobs#328
So I ran the job in prod, and it's finding ones that shouldn't be deleted for some reason. so revert for now until we can understand why that's happening
see `runtime_anomalies` tab in https://docs.google.com/spreadsheets/d/1L4xMydpufZsYWYaZ4AleZwemJVLSdrePxFXVoBvfNFg/edit#gid=145896178
> Revert "IA-4823 look for runtimes without destroyedDate as well"

- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
1. Add back the `destroyedDate` condition from previous reverted PR
2. Fix a bug where we're detecting some runtimes as anomalies incorrectly.
Here's the bug. Take the following as an example
```
123099, all-of-us-6490, terra-vpc-sc-60fd067e, Deleted, 2023-11-12 00:48:55.071059, 2023-11-12 01:21:27.304278...
149253, all-of-us-6490, terra-vpc-sc-60fd067e, Stopping, 2024-03-18 00:48:55.071059, 1970-01-01 00:00:01.000000...
```
123099 should've been excluded becuz 149253 is in the same project with the same name that is still active (this is because AoU re-uses runtime names when creating new runtimes in the same project for the same user). But the query condition is not excluding 123099 because 149253's status is `Stopping` and the `NOT EXISTS` is only looking for `Stopped` and `Running` …
> IA-4871  Include destroyedDate in the deletedRuntime checker and fix a bug where we're including runtimes that shouldn't have been deleted

- zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedDiskCheckerSpec.scala
Before proceeding with changing Zombie Monitor behavior (as described [here](https://docs.google.com/document/d/1BR71eX5mWjXUoHRTYs0dMjGJe6eXa3K5sLO7neVn6So/edit)), I wanted to add some unit tests in order to verify current behavior. These will be helpful to test against when changing cron job behavior in a future ticket.
> RW-12296 Added unit tests for zombieMonitor DeletedDiskChecker

- zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedDiskChecker.scala
- zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedDiskCheckerSpec.scala
Follow up to https://github.com/broadinstitute/leonardo-cron-jobs/pull/331. 
Behavior of this cron job is that it currently updates disk status when it encounters a PermissionDenied exception with a message that contains either “Compute Engine API has not been used” or “This API method requires billing to be enabled” and isDryRun = false.
Both of these messages will no longer update disk status.
Tested this by running `sbt "zombieMonitor/run --checkDeletedDisks"`with cloud-sql container running, so the cron job ran against dev.
> RW-12296 Changed cron job so that it no longer calls updateDiskStatus when the getDisk endpoint encounters a billing error.

- janitor/src/main/scala/com/broadinstitute/dsp/janitor/DbReader.scala
Currently, Janitor looks for non deleted clusters that do not have users nodepools which have active apps. With autopilot, apps will "live" on default nodepools from leo's perspective, so we're updating the query to look for non deleted clusters that do not have nodepools which have active apps regardless whether the nodepool is default or not.
> RW-12864 Remove isDefault filter on nodepool

- janitor/src/main/scala/com/broadinstitute/dsp/janitor/KubernetesClusterRemover.scala
- janitor/src/main/scala/com/broadinstitute/dsp/janitor/NodepoolRemover.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/KubernetesClusterRemoverSpec.scala
- janitor/src/test/scala/com/broadinstitute/dsp/janitor/NodepoolRemoverSpec.scala
- resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala
- resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolCheckerSpec.scala
`NonLeoMessageSubscriber` is supposed to process messages like deletek8sCluster...There was a recent change that `leonardo=true` is added to the msgs sent by janitor, this makes it such that `LeoPubsubSubscriber` will process these msgs instead of `NonLeoMessageSubscriber` (see [this])(https://github.com/DataBiosphere/leonardo/blob/develop/http/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/config/Config.scala#L846)
and as a result we see this error
```
Subscriber fail to decode message data: "{\"messageType\":\"deleteKubernetesCluster\",\"clusterId\":2178,\"project\":\"terra-vpc-sc-dev-68bb7540\",\"traceId\":\"kubernetesClusterRemover-2024-06-20T12:00:20.245464Z\"}"
attributes {
key: "leonardo"
value: "true"
}
message_id: "10206832210185558"
publish_time {
seconds: 1718884820 …
```
> RW-12921 Don't add leonardo=true tag
