resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/BucketRemover.scala
Minor fix:
Currently, we're blindly reporting all staging bucket candidates that are need to be deleted because to be more accurate, previously I thought we need to make an additional `getBucket` call, but now that I look at `deleteBucket` API, it's returning `true` when the deletion actually happened, and `false` if not found, hence we can tell if a bucket was deleted fairly easily.
=> [no ticket] make staging bucket report a bit more accurate

README.md
Update instructions how you can run a job locally
=> IA-2257 add more guideline

resource-validator/src/main/resources/reference.conf
`report-destination-bucket` will be put in application.conf in https://github.com/broadinstitute/terra-helm/pull/165
=> [no ticket] remove report-destination-bucket from being populated from environment variable

.github/workflows/unitTests.yml, README.md, core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala, core/src/main/scala/com/broadinstitute/dsp/checkerDeps.scala, core/src/main/scala/com/broadinstitute/dsp/models.scala, core/src/test/scala/com/broadinstitute/dsp/CronJobsTestSuite.scala, core/src/test/scala/com/broadinstitute/dsp/DBTestHelper.scala, core/src/test/scala/com/broadinstitute/dsp/Generators.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DbReaderSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedDiskCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitDependenciesHelper.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErrorRuntimeChecker.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredNodepoolChecker.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredRuntimeChecker.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/Main.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ZombieMonitor.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DbReaderSpec.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredNodepoolCheckerSpec.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredRuntimeCheckerSpec.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/mocks.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/package.scala
https://broadworkbench.atlassian.net/browse/IA-2232
=> IA-2232 scan runtimes as well

.github/workflows/createPullRequest.yml, core/src/main/scala/com/broadinstitute/dsp/CheckRunner.scala
https://broadworkbench.atlassian.net/browse/IA-2220
=> IA-2220 One more try to fix create pull request workflow

.scalafmt.conf, core/src/main/scala/com/broadinstitute/dsp/CheckRunner.scala, core/src/main/scala/com/broadinstitute/dsp/checkerDeps.scala, core/src/test/scala/com/broadinstitute/dsp/CronJobsTestSuite.scala, project/Dependencies.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedDiskCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitBucketCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitDependenciesHelper.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/KubernetesClusterRemoverSpec.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ZombieMonitor.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredNodepoolCheckerSpec.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredRuntimeCheckerSpec.scala
https://broadworkbench.atlassian.net/browse/IA-2312
Related PR https://github.com/DataBiosphere/leonardo/pull/1670
=> IA-2312 Add metrics for each check type

resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/Main.scala
I guess at the time, I was really nervous about turning off dryRun lol
=> [no ticket] fix option

zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/mocks.scala
https://broadworkbench.atlassian.net/browse/IA-2331
=> IA-2331 update deletedFrom

core/src/main/scala/com/broadinstitute/dsp/checkerDeps.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitDependenciesHelper.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredRuntimeChecker.scala, zombie-monitor/src/test/scala/com/broadinstitute/dsp/zombieMonitor/DeletedOrErroredRuntimeCheckerSpec.scala
https://broadworkbench.atlassian.net/browse/IA-2458
1. If cluster is in Error due to billing disabled, update this in DB
2. Add `deleteFrom` to `zombie cron job` if runtime is marked as Deleted from zombie job
=> IA-2458 if billing is disabled, update Error cause properly

.github/workflows/trivy.yml, core/src/main/scala/com/broadinstitute/dsp/models.scala, project/Settings.scala
This change adds Trivy security scan for the Docker image, as discussed in the Workbench Cross-Team meeting.
The action will run on every PR and give you feedback if the Docker image contains critical OS vulnerabilities.
More info:
https://github.com/broadinstitute/dsp-appsec-trivy-action
https://github.com/broadinstitute/dsp-appsec-blessed-images
=> [IA-2343] Add AppSec GitHub Trivy Action

core/src/main/scala/com/broadinstitute/dsp/CheckRunner.scala, core/src/main/scala/com/broadinstitute/dsp/models.scala, core/src/test/scala/com/broadinstitute/dsp/Generators.scala, project/Settings.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/KubernetesClusterRemover.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/NodepoolRemover.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DBReaderGetNodepoolsToDeleteSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/NodepoolRemoverSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/mocks.scala
Tested in dev, there were a lot of hits. 
This is related to this PR https://github.com/DataBiosphere/leonardo/pull/1806, but can be merged independently.
=> [IA-2395] Cleanup nodepools with no apps

resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DataprocWorkerChecker.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DataprocWorkerCheckerSpec.scala
https://broadworkbench.atlassian.net/browse/IA-2500
=> [IA-2500] don't report anomaly if preemptibles in google is 0

build.sbt, core/src/main/scala/com/broadinstitute/dsp/package.scala, core/src/test/scala/com/broadinstitute/dsp/DBTestHelper.scala, project/Dependencies.scala, project/Settings.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ZombieMonitor.scala
https://broadworkbench.atlassian.net/browse/IA-2589
Was too confident about the change in previous PR lol...it had some dependency conflicts
=> IA-2589 bump a few dependencies

core/src/main/scala/com/broadinstitute/dsp/models.scala, core/src/main/scala/com/broadinstitute/dsp/package.scala, core/src/test/scala/com/broadinstitute/dsp/DBTestHelper.scala, core/src/test/scala/com/broadinstitute/dsp/Generators.scala, project/Dependencies.scala, project/Settings.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedDiskChecker.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedDiskChecker.scala
https://broadworkbench.atlassian.net/browse/IA-2589
=> IA-2589 remove default zone reference

.scalafmt.conf, project/Dependencies.scala, project/Merging.scala, project/Settings.scala, project/plugins.sbt, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DataprocWorkerCheckerSpec.scala
https://broadworkbench.atlassian.net/browse/IA-3005
=> IA-3005 Bump a few dependency versions

core/src/main/scala/com/broadinstitute/dsp/models.scala, janitor/src/main/resources/logback.xml, janitor/src/main/scala/com/broadinstitute/dsp/janitor/Janitor.scala, nuker/src/main/resources/logback.xml, project/Settings.scala, project/Version.scala, resource-validator/src/main/resources/logback.xml, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala, zombie-monitor/src/main/resources/logback.xml, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ZombieMonitor.scala
https://broadworkbench.atlassian.net/browse/IA-3086
Similar to how we do things in Leonardo
=> IA-3086 set up logging in a way that error reporting can recognize the service

core/src/main/scala/com/broadinstitute/dsp/package.scala
just to update `core` to trigger rebuild of janitor and zombiemonitor
=> [no ticket] dummy change

core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala, core/src/main/scala/com/broadinstitute/dsp/checkerDeps.scala, core/src/main/scala/com/broadinstitute/dsp/models.scala, core/src/test/scala/com/broadinstitute/dsp/Generators.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedRuntimeChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ErroredRuntimeChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/StoppedRuntimeChecker.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/ActiveRuntimeChecker.scala
Noticing these errors in the last few runs: 2022-03-28 04:48:44.937 EDTdoobie.util.invariant$InvalidValue: AZURE_VM: String invalid for com.broadinstitute.dsp.CloudService because: invalid cloudService value AZURE_VM
Added a TODO for once we support Azure clean up
=> [IA-3281] Fixing Resource Validator

core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala, core/src/main/scala/com/broadinstitute/dsp/models.scala, core/src/test/scala/com/broadinstitute/dsp/Generators.scala, janitor/src/main/scala/com/broadinstitute/dsp/janitor/DbReader.scala, janitor/src/main/scala/com/broadinstitute/dsp/janitor/KubernetesClusterRemover.scala, janitor/src/main/scala/com/broadinstitute/dsp/janitor/NodepoolRemover.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredKubernetesClusterChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala
https://broadworkbench.atlassian.net/browse/IA-3622
=> IA-3622 accomodate app schema change

core/src/main/scala/com/broadinstitute/dsp/models.scala
dummy change in `core` dir to trigger rebuild of images
=> IA-3631 dummy PR to trigger rebuild of images

zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DeletedDiskChecker.scala
https://broadworkbench.atlassian.net/browse/IA-3243
Some of the disks stuck in `Deleting` is because their project is disabled or `Compute API` is disabled for these projects. In those cases, zombieMonitor should just go ahead and mark these disks as `Deleted` from Google.
Tested against dev
=> IA-3243 mark non-existent disks as `Deleted`

core/src/main/scala/com/broadinstitute/dsp/DbReaderImplicits.scala, core/src/main/scala/com/broadinstitute/dsp/models.scala, janitor/src/main/resources/reference.conf, janitor/src/main/scala/com/broadinstitute/dsp/janitor/NodepoolRemover.scala, resource-validator/src/main/resources/reference.conf, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala, zombie-monitor/src/main/scala/com/broadinstitute/dsp/zombieMonitor/DbReader.scala
Tested resource validator and zombie monitor locally
=> [IA-4805] bug fix in zombie monitor/resource validator caused from last PR

resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DbReader.scala
I'm having trouble validating locally...but wanna get this out while working on verifying locally and adding a test
=> IA-4823 hopefully fix syntax

core/src/main/scala/com/broadinstitute/dsp/CheckRunner.scala, core/src/main/scala/com/broadinstitute/dsp/checkerDeps.scala, janitor/src/main/scala/com/broadinstitute/dsp/janitor/Janitor.scala, janitor/src/main/scala/com/broadinstitute/dsp/janitor/KubernetesClusterRemover.scala, janitor/src/main/scala/com/broadinstitute/dsp/janitor/NodepoolRemover.scala, janitor/src/test/scala/com/broadinstitute/dsp/janitor/KubernetesClusterRemoverSpec.scala, janitor/src/test/scala/com/broadinstitute/dsp/janitor/NodepoolRemoverSpec.scala, janitor/src/test/scala/com/broadinstitute/dsp/janitor/StuckAppReporterSpec.scala, project/Dependencies.scala, project/Merging.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolChecker.scala, resource-validator/src/main/scala/com/broadinstitute/dsp/resourceValidator/ResourceValidator.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/DeletedOrErroredNodepoolCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitBucketCheckerSpec.scala, resource-validator/src/test/scala/com/broadinstitute/dsp/resourceValidator/InitDependenciesHelper.scala
Bump to include google2 library change https://github.com/broadinstitute/workbench-libs/pull/1669
=> [IA-4578] bump workbench-libs google2 version

README.md
The old readme referenced the deprecated `terra-helm`.
=> Readme contributing steps
